#!/bin/bash
#o
#e
# bsub -q 1nw -J cascade < cascade-myrivet.sub
source /afs/cern.ch/sw/lcg/external/MCGenerators/powhegbox/r197/slc4_amd64_gcc34/bin/setup.sh
pwd=`pwd`
echo $pwd
name=$LS_JOBNAME
seed=$LS_SEED

ls -rtl 

cp -rp /afs/cern.ch/work/r/rkunnawa/WORK/RAA/pp_genjets_pythia_NPC/Powheg_cross_check/scripts/powheg_submission_scripts/powheg.input .

TheSeed=${seed}
Templatefile=powheg.input
Targetfile=powheg-new.input
sed s/MYSEED/${TheSeed}/ ${Templatefile} > ${Targetfile}
cp powheg-new.input powheg.input

/afs/cern.ch/sw/lcg/external/MCGenerators/powhegbox/r197/slc4_amd64_gcc34/bin/Dijet > ${name}.out

cp ${name}.out /afs/cern.ch/work/r/rkunnawa/WORK/RAA/pp_genjets_pythia_NPC/Powheg_cross_check/
mv *.lhe ${name}.lhe
sed '$d' < ${name}.lhe > temp_${name}.lhe
mv temp_${name}.lhe ${name}.lhe
cp ${name}.lhe /afs/cern.ch/work/r/rkunnawa/WORK/RAA/pp_genjets_pythia_NPC/Powheg_cross_check/